#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: recording the gesture clip set (#16)
# ──────────────────────────────────────────────────────────────────────────
#
# Each clip: 10 s of webcam, split into JPEGs (kept in ~/.cache), tracked
# into replay frames, and run through today's desktop control as a dry run.
# The repo keeps frames.json, dryrun.log and intent.md per clip, for the
# golden replays (#18). Re-running offers to keep clips already recorded.

ROOT=$(cd "$(dirname "$0")/.." && pwd)
TARGET=${CARGO_TARGET_DIR:-$HOME/cs/terrain/target}
REPLAY_CLIP=$TARGET/release/examples/replay_clip
REPLAY_DESKTOP=$TARGET/release/examples/replay_desktop
RAW=$HOME/.cache/terrain/clips/gestures
OUT=$ROOT/crates/terrain-desktop/tests/clips
CAMERA=/dev/video0
SECONDS_PER_CLIP=10

TOTAL_STAGES=11

# camera_free waits until no other program holds the camera.
camera_free() {
  while fuser "$CAMERA" >/dev/null 2>&1; do
    warn "$CAMERA is in use (terrain-app or terrain-desktop running?). Close it."
    pause "Press Enter once it's closed"
  done
}

# record NAME captures SECONDS_PER_CLIP of 720p MJPEG into $RAW/NAME.mjpg,
# showing the clip time so the timeline can be followed.
record() {
  local mjpg="$RAW/$1.mjpg" s pid
  camera_free
  for s in 3 2 1; do printf '\r  %sstarting in %s…%s ' "$YELLOW" "$s" "$RESET"; sleep 1; done
  v4l2-ctl -d "$CAMERA" --set-fmt-video=width=1280,height=720,pixelformat=MJPG \
    --stream-mmap=4 --stream-count=$((SECONDS_PER_CLIP * 30)) --stream-to="$mjpg" 2>/dev/null &
  pid=$!
  for ((s = 0; s < SECONDS_PER_CLIP; s++)); do
    printf '\r  %s● REC  t = %2d s%s        ' "$RED$BOLD" "$s" "$RESET"
    sleep 1
  done
  wait "$pid"
  printf '\r  %s■ done%s                 \n' "$GREEN" "$RESET"
}

# clip NAME TITLE DO EXPECT: one recorded take, retaken until kept.
clip() {
  local name="$1" title="$2" todo="$3" expect="$4" dir="$OUT/$1"
  stage "$title"
  if [[ -f "$dir/frames.json" ]] && ! confirm "Already recorded. Record it again?"; then
    return
  fi
  while true; do
    stage_body "$todo" "$expect"
    pause "Get in place, then press Enter to record ${SECONDS_PER_CLIP} s"
    record "$name"
    rm -rf "${RAW:?}/$name"
    mkdir -p "$RAW/$name" "$dir"
    ffmpeg -loglevel error -f mjpeg -i "$RAW/$name.mjpg" -c:v copy "$RAW/$name/f%03d.jpg"
    note "tracking hands…"
    "$REPLAY_CLIP" "$RAW/$name" --every-frame --save-frames "$dir/frames.json" >/dev/null
    "$REPLAY_DESKTOP" "$dir/frames.json" > "$dir/dryrun.log"
    printf '\n  %sToday'"'"'s desktop control would do:%s\n' "$BOLD" "$RESET"
    sed 's/^/    /' "$dir/dryrun.log"
    printf '\n'
    if confirm "Keep this take? (n retakes it)"; then break; fi
    _clear
    printf '\n%s%s▸ Retake · %s%s\n' "$BOLD" "$BLUE" "$title" "$RESET"
  done
  {
    printf '# %s\n\n## Performed\n\n%s\n\n## Expected actions\n\n%s\n' "$title" "$todo" "$expect"
  } > "$dir/intent.md"
  printf '  %s✓ saved%s %s\n' "$GREEN" "$RESET" "${dir#"$ROOT"/}"
  pause
}

stage_body() {
  printf '\n  %sDo this%s (seated as usual; t is clip time):\n' "$BOLD" "$RESET"
  printf '%s\n' "$1" | sed 's/^/    /'
  printf '\n  %sShould come out as%s:\n' "$BOLD" "$RESET"
  printf '%s\n' "$2" | sed 's/^/    /'
  printf '\n'
}

# Every clip starts the same way: take control.
RAISE="t 0–2  hands on the keyboard
t 2–3  raise your right hand open, palm to the camera, to chest height in
       front of the screen; hold it still for a full second"
LOWER="lower the hand back to the keyboard and leave it there to the end"

banner "Record the gesture clip set (#16)"

stage "Camera check"
for tool in v4l2-ctl ffmpeg fuser; do
  command -v "$tool" >/dev/null || { warn "$tool is missing; install it and re-run"; exit 1; }
done
for bin in "$REPLAY_CLIP" "$REPLAY_DESKTOP"; do
  [[ -x "$bin" ]] || { warn "missing $bin; build it with:"; note "CARGO_TARGET_DIR=$TARGET cargo build --release -p terrain-hands --example replay_clip -p terrain-desktop --example replay_desktop"; exit 1; }
done
mkdir -p "$RAW" "$OUT"
camera_free
say "Grabbing one frame so you can check the camera's view."
v4l2-ctl -d "$CAMERA" --set-fmt-video=width=1280,height=720,pixelformat=MJPG \
  --stream-mmap=4 --stream-count=15 --stream-to="$RAW/check.mjpg" 2>/dev/null
ffmpeg -loglevel error -y -sseof -0.1 -f mjpeg -i "$RAW/check.mjpg" -frames:v 1 "$RAW/check.jpg" 2>/dev/null \
  || ffmpeg -loglevel error -y -f mjpeg -i "$RAW/check.mjpg" -frames:v 1 "$RAW/check.jpg"
open_url "$RAW/check.jpg"
step "Sit as you do when using the desktop by hand."
step "Check the view: a hand raised at chest height should sit well inside it."
pause "Camera where you want it? Press Enter"

clip tap "Tap" \
"$RAISE
t 4    pinch thumb to index quickly and open again (under half a second)
t 5–7  hold the hand open and still
t 7    $LOWER" \
"- the hand takes control
- exactly one left click (Press Left, Release Left) where the hand pointed
- no drag, no right click, no window drag
- control let go after the hand is lowered"

clip drag "Drag" \
"$RAISE
t 4    pinch and start moving right at once: a pinch held still for
       over half a second is a long press (right click)
t 4–6  keep pinching while moving about 20 cm to your right
t 6    open the hand; hold it still for a second
t 7    $LOWER" \
"- the hand takes control
- Press Left at the point where the pinch closed, the pointer moves right,
  then Release Left when the hand opens
- no other buttons
- control let go after the hand is lowered"

clip long_press "Long press" \
"$RAISE
t 4    pinch, and hold the pinch perfectly still
t 4–6  keep holding still (2 s)
t 6    open the hand; hold it still for a second
t 7    $LOWER" \
"- the hand takes control
- one right click (Press Right, Release Right) about 0.6 s after the pinch
  closed, where the hand pointed
- no left click
- control let go after the hand is lowered"

clip vee_up "Vee scroll up" \
"$RAISE
t 4    make a Vee: index and middle fingers up, the others curled
t 4–5  move the Vee up about 10 cm
t 5–7  hold it there (2 s)
t 7–8  bring it back to where the Vee began, then open the hand
t 8    $LOWER" \
"- the hand takes control
- PENDING until Vee exists (#22): scrolls up while the Vee is above where
  it began, faster the further up; stops when it returns; the pointer stays
  frozen; no buttons
- control let go after the hand is lowered"

clip vee_down "Vee scroll down" \
"$RAISE
t 4    make a Vee: index and middle fingers up, the others curled
t 4–5  move the Vee down about 10 cm
t 5–7  hold it there (2 s)
t 7–8  bring it back to where the Vee began, then open the hand
t 8    $LOWER" \
"- the hand takes control
- PENDING until Vee exists (#22): scrolls down while the Vee is below where
  it began; stops when it returns; the pointer stays frozen; no buttons
- control let go after the hand is lowered"

clip vee_sideways "Vee scroll sideways" \
"$RAISE
t 3    make a Vee: index and middle fingers up, the others curled
t 3–5  move the Vee about 10 cm right and hold it there
t 5–7  move it about 10 cm left of where it began and hold it there
t 7–8  bring it back to where the Vee began, then open the hand
t 8    $LOWER" \
"- the hand takes control
- PENDING until Vee exists (#22): scrolls right, then left; stops when it
  returns; the pointer stays frozen; no buttons
- control let go after the hand is lowered"

clip fist_drag "Fist window drag" \
"Before recording: put a floating window under where you'll point.
$RAISE
t 4    close the hand into a fist
t 4–6  move the fist slowly about 20 cm to your right
t 6    open the hand; hold it still for a second
t 7    $LOWER" \
"- the hand takes control
- Press Super, Press Left, the pointer moves right, Release Left,
  Release Super: one window drag
- no plain left click, no right click
- control let go after the hand is lowered"

clip fist_forming "Fist forming (no click)" \
"$RAISE
t 4–5  slowly curl the open hand into a fist (about a second)
t 5–6  hold the fist still
t 6–7  slowly open it again; hold open
t 8    $LOWER" \
"- the hand takes control
- at most one window drag (Super + Left pressed, then released) with the
  pointer still
- never a left click or right click from the pinch the hand passes through
- control let go after the hand is lowered"

clip typing "Typing (no control)" \
"Before recording: put the cursor in a scratch text field or terminal.
t 0–10 type with both hands on the keyboard the whole time, as normal;
       reach for the mouse once if you like, but never raise a hand open
       toward the screen" \
"- no hand takes control
- no actions at all: no pointer moves, no buttons"

clip leave_mid_drag "Hand leaves mid-drag" \
"$RAISE
t 4    pinch and start moving right at once: a pinch held still for
       over half a second is a long press (right click)
t 4–7  keep pinching while dragging slowly to your right, on past the
       screen's edge, until the hand leaves the camera's view (slowly: a
       fast sweep blurs the pinch open, which ends the drag early)
t 7–10 keep it out of view, still pinched" \
"- the hand takes control
- Press Left at the pinch, the pointer moves right, then Release Left
  within about 0.3 s of the hand vanishing
- nothing left held; control let go"

finish
note "Clips are in ${OUT#"$ROOT"/} (frames.json, dryrun.log, intent.md each)."
note "Raw JPEGs are in $RAW. Tell Claude to check them for #16 and #18."
